### ISSUE TITLE
Is CocoaPods really necessary?

### ISSUE THREAD

**Issue by i-schuetz** [shekohex/flutterust#5]
I was looking into the iOS dependencies and found that you use CocoaPods. I've tried to avoid this dependency manager in my recent iOS projects as it's a bit unwieldy and invasive. For the binaries, did you consider linking them directly to the project? So you don't need a 3d party? I see it's also used to link to Flutter. Why is this needed (genuine question)? A standard Flutter project in any case isn't created with CocoaPods, from what I can see.

**Comment by shekohex** [comment]
I agree with you about CocoaPods,
It's hard to link binaries to Flutter project without that, the trick here that we let other system to do that for us, creating a Flutter Plugin using `flutter create --template plugin` will generate that template which includes CocoaPods

Otherwise, it will require using Xcode and configure some stuff to link a lib directly to the project without using the plugin template, Also the FFI would be written in the project itself, not in separate plugin/package

**Comment by i-schuetz** [comment]
Yeah, I just read in the Flutter repo that CocoaPods is the default way to manage plugins. Hope that they can/will change it (not sure about the internals) at some point to SPM, which should start supporting binaries with Swift 5.3.
