### ISSUE TITLE
Does it require unsafe blocks for returning strings or structs?

### ISSUE THREAD

**Issue by shujaatak** [shekohex/flutterust#7]
I have read the following statement in a similar repository name [flutter-rust-ffi](https://github.com/brickpop/flutter-rust-ffi): 
`Returning strings or structs may require using unsafe blocks. Returned strings or structs will need to be free'd from Dart.`
I wonder if the same applies here too?

**Comment by shekohex** [comment]
Simple Answer: Yes and No.

- **Yes** if you are willing to use `Raw`-ptr for Structs and any other types.
 But, Note that managing raw pointers will require you heap-allocate (aka `Box`-ing values) and add `finalizer` to be called when `Dart` does not need the object/pointer anymore, otherwise that will introduce memory issues.
So, Simply you will have code looks like this:
```rust
struct User {
  id: u32,
  active: bool,
}

#[no_mangle]
pub unsafe extern "C" fn user_new(id: u32) -> *const User {
  let user = User { id, active: true };
  let boxed = Box::new(user);
  Box::into_raw(boxed) as _
}

#[no_mangle]
pub unsafe extern "C" fn user_free(ptr: *const User) {
  let _ = Box::from_raw(ptr);
}

```
> Please Forgive if that does not compile, I wrote it on GitHub directly 😄 

- **No** if you are using some sort of `async` Dart/Rust because you don't need to manage the memory yourself, instead you convert your types into raw `Dart` types and send them to the `VM` then you simply drop your value, because the value you sent to the `Dart VM` Get Copied/Cloned and managed by the `VM` as a normal Dart object.

This was very easy to do since we built [`allo-isolate`](https://docs.rs/allo-isolate), take a look at the docs and the example [here](https://github.com/shekohex/flutterust/blob/af93e9da201ef514d261a390df9aff83c1e14bdb/native/scrap-ffi/src/lib.rs#L65), For Real-World Usage take a look at [Sunscreen](https://github.com/sunshine-protocol/sunscreen) our mobile app for [Sunshine](https://github.com/sunshine-protocol).
